### ISSUE TITLE
Setting a Project Name different than the Plugin Name could cause errors

### ISSUE THREAD

**Issue by Rulox** [moxie-lean/generators#19]
**Steps to reproduce and a minimal demo of the problem**
1. Run the generator.
2. Choose a name for the project.
3. Choose a different name for the plugin.

**Current behavior**
The external travis file (maybe others) selects the 'Project Name' as the plugin name, so it generates things like `cd wp-content/plugins/{ProjectName}` instead of `cd wp-content/plugins/{PluginName}`

**Expected/desired behavior**
We should be able to select different Plugin/Project names and the files should be generated accordingly.

**Other information**

**Comment by adamf321** [comment]
The issue now is they are 2 different generators, we would need to figure out how to make them interact.

Another option is to force them to always be the same.

**Comment by Rulox** [comment]
I see. Can't we store the variable in a temp file? So the second generator can look for that file and , if exists, do the changes?

**Comment by adamf321** [comment]
Maybe... we'll have to search for best practices. In the meantime we can just use the same name for both. Does that cause an issue?

**Comment by mitogh** [comment]
Is working fine on my end would you mind providing more information about this?

**Comment by adamf321** [comment]
It's already fixed here: https://github.com/moxie-lean/generators/pull/20

**Comment by mitogh** [comment]
Doh! the comment it was supposed to be placed on the PR. 😆
