### ISSUE TITLE
Generator should not allow to start the Plugin Name with a number

### ISSUE THREAD

**Issue by Rulox** [moxie-lean/generators#22]
**Steps to reproduce and a minimal demo of the problem**
1- Run the generator
2- Select a plugin name starting with a numbre (ie 8760)

**Current behavior**
PHP does not allow to use variable or const names starting with numbers, so the plugin won't work at all.

**Expected/desired behavior**
We should be aware of this and don't allow the user to enter a number as the plugin name.

**Other information**

**Comment by mitogh** [comment]
Why? 🥺

**Comment by Rulox** [comment]
I'm doing issue cleaning, nothing else! Maintainers can reopen if needed if this is being used @mitogh

**Comment by mitogh** [comment]
JK, go for it :100: 

>  if this is being used

:thinking:
