### ISSUE TITLE
Post update script is not executing?

### ISSUE THREAD

**Issue by Rulox** [moxie-lean/generators#26]
**Steps to reproduce and a minimal demo of the problem**
- Create a new wp project using the generator `yo moxie-lean:new-wp` 
- Run composer update to update lock and install plugins

**Current behavior**
- The post-update-cmd script is not being called

**Expected/desired behavior**
- The script should be fired after the update.

**Other information**

I don't know if this is only a problem on my end, but the wordpres-seo `composer install` command is not working after doing a `composer update` in root, you can check this by running the `composer install` in the wordpress-seo plugin dir manually.

PS: Also, shouldn't we run the composer update after the composer.json file is created automatically so all the plugins are installed and the project is ready 100%? What do you think? cc @mitogh @adamf321

**Comment by mitogh** [comment]
I think this get's fixed with: https://github.com/moxie-lean/generators/pull/20
