### ISSUE TITLE
Better treatment of complex plugin names.

### ISSUE THREAD

**Issue by Rulox** [moxie-lean/generators#27]
**Steps to reproduce and a minimal demo of the problem**
1. Use the generator to create a plugin.
2. Name the plugin with more than one word, for example: `lean-plugin-api`

**Current behavior**
- Namespaces: Generator will create a only namespace called `MyPluginApi`
- Constants: Name of the constant will be `MYPLUGINAPI`

**Expected/desired behavior**
- Namespace should be `Lean\Plugin\Api`
- Constants should be like `MY_PLUGIN_API`

**Other information**
N/A

---

What do you think about this?

**Comment by adamf321** [comment]
I think we need a new generator. The wp-plugin one is very specific to creating a base plugin for one of our projects.

**Comment by mitogh** [comment]
I think both issues are present if we are creating a plugin for a project with the same pattern specified above.

**Comment by adamf321** [comment]
I don't see why we'd ever want to create one with a 3-level nested namespace like this. Generated constant names could be improved.

**Comment by mitogh** [comment]
A solution might be ask for the namespace and if is empty we use the default value (as happens with NPM or Composer). 

And the problem exist on constants regardless of the input.
